version: 2.1

jobs:
  store_artifacts:
    parameters:
      path:
        type: string
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - store_artifacts:
          path: << parameters.path >>
      - run: echo done
workflows:
  main:
    jobs:
      - store_artifacts:
          matrix:
            parameters:
              path:
                - static
                - does_not_exist
